version: '3.8'

services:
  bayes-hs:
    build: ./
    command: cabal run bayes-hs -- +RTS -N
    depends_on:
      - scrap-servise
    ports:
      - 8081:8081
    environment:
      - NORMALIZER_URL=http://scrap-servise:1207/

  scrap-servise:
    image: normalizer    
    depends_on:
      - redis
    ports:
      - 1207:1207
    env_file:
      - "../ua-word-normalizer/.env"
      
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass verysecretpassword
